FROM rust:1.70.0-slim-bullseye

RUN apt update -y && apt upgrade -y && apt install -y \
    build-essential \
    curl \
    git \
    libssl-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /repo

